# Generated by Django 4.2.5 on 2023-10-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_country_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('XX', 'Другая страна'), ('OS', 'Южная Осетия'), ('LT', 'Литва'), ('MD', 'Молдова'), ('KZ', 'Казахстан'), ('RU', 'Россия'), ('KG', 'Киргизия'), ('LV', 'Латвия'), ('AM', 'Армения'), ('CK', 'Острова Кука'), ('GE', 'Грузия'), ('BY', 'Беларусь'), ('UZ', 'Узбекистан')], max_length=25, null=True, verbose_name='страна'),
        ),
    ]
