# Generated by Django 4.2.5 on 2023-10-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.CharField(default=1, max_length=50, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
