# Generated by Django 4.2.5 on 2023-10-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_author_product_created_by_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_by_user',
            new_name='producer',
        ),
    ]
